// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  customer_logos: dynamic(() => import("./CustomerLogos")),
  hero: dynamic(() => import("./Hero")),
  hero_component: dynamic(() => import("./HeroComponent")),
};
